### ISSUE TITLE
[BUG] Invoices always have `complete` as `true` regardless of payment status

### ISSUE THREAD

**Issue by Gfloresechaiz** [andrerfneves/lightning-decoder#12]
Maybe I'm not understanding something, let me know if that is the case.
but no matter if the invoice is paid or not, tx-complete shows as : true.
Otherwise, great tool!

**Comment by andrerfneves** [comment]
@Gfloresechaiz totally missed the notification for this. Good point raised. I'll try and debug it myself and see what's happening. Could be poor manipulation of the BOLT 11 string. I'll try and find sometime the next couple of days to check this out.

**Comment by andrerfneves** [comment]
Resolved
