### ISSUE TITLE
simnet addresses not working

### ISSUE THREAD

**Issue by ottosuess** [andrerfneves/lightning-decoder#23]
lnsb10n1pwemvgrpp5682zm9zc4jp3yzr69lvqnwxzj3e9qh9q0xyf8fq6xed6pgex37rqdqqcqzpgxq97zvuqh6r9xwxyg5kwlaz3tkm00fx6zyr7m43lp95tk0drkng2ysex7xsxva9ky3ggw3uuae2rdfvls0j2m3vdxzs7vdxxvskxguds3q0ewxqqh7nys7

```
Unknown coin bech32 prefix
```

**Comment by andrerfneves** [comment]
Addressed and will be deployed on next release.
