### ISSUE TITLE
403 when decoding invoice from taproot.watch

### ISSUE THREAD

**Issue by pysiak** [andrerfneves/lightning-decoder#45]
https://taproot.watch has a lightning invoice:
lnurl1dp68gurn8ghj7arpwpex7mm59emkzarrdqhkjmnkda5kxeguysm5q

When I input it in https://lightningdecoder.com/ it says 403

**Comment by andrerfneves** [comment]
Bug confirmed. Will investigate.

**Comment by andrerfneves** [comment]
https://github.com/Rob--W/cors-anywhere/issues/301

Investigating an alternative

**Comment by jsarenik** [comment]
I get the same error when trying to decode any lnurl from satoshi_LN_bot on Twitter: e.g. `lnurl1dp68gurn8ghj7ctsdyhxyarrxfkxutnrdakj7cmgv43kkurp09hh2ap0wpshjmm4w34k27favfsnydm9xumkzvtxvccrqenpxyuxyde389jk2cmxvcmxxdrzep6lmz`

**Comment by andrerfneves** [comment]
@jsarenik this has been fixed in the latest version. Already deployed to lightningdecoder.com. Let me know if it works.

**Comment by jsarenik** [comment]
@andrerfneves Thank you for feed-back!

For what I am trying it does not work. But the error message is different now, so opening a [new issue](https://github.com/andrerfneves/lightning-decoder/issues/60) #60

**Comment by jsarenik** [comment]
And another follow-up is #61
