### ISSUE TITLE
invoice as query parameter?

### ISSUE THREAD

**Issue by kiwiidb** [andrerfneves/lightning-decoder#52]
I think it would be super useful to have the invoice/lnurl string as a query parameter, so you can check an invoice in one click. Unfortunately I've never used React so I don't really know how to implement this.

**Comment by andrerfneves** [comment]
This is a great idea. Will implement.

**Comment by andrerfneves** [comment]
https://lightningdecoder.com/lnbc1110n1ps0ng2dpp5k7x5s2mpq8q8lsxm030mvv7sfged4sflz3ypuywp3s6sv70fhqdsdpvf35kw6r5de5kueeqga5kvapqvehhygp3xycjqumpw3escqzpgxqyz5vqsp5kt2e6n870cd6yj6al7acs8kl0vd76jpcxfpekrwmyfjnh0gj4v6q9qyyssq0rsnjv7ng8nj0e5fdghd547rzqt5fja4uq58ll0jy0gq3ymzhfr8nre6m9283un8e73q2uueqma2a7z425fz7qtkzty6knrgf5k9jyspx202fr

Resolved and deployed
