### ISSUE TITLE
BOLT 12 offer support?

### ISSUE THREAD

**Issue by Sjors** [andrerfneves/lightning-decoder#56]
Still experimental, but would be nice:
https://lightning.readthedocs.io/lightning-offer.7.html

**Comment by andrerfneves** [comment]
Not a bad idea. Is there a JS lib that decodes bolt12 already?

**Comment by adi2011** [comment]
https://www.npmjs.com/package/bolt12
This can help.

**Comment by andrerfneves** [comment]
Stale, closing for now.
