### ISSUE TITLE
website assumes wrong url

### ISSUE THREAD

**Issue by j-chimienti** [andrerfneves/lightning-decoder#66]
Issue:

fork and deploy code to github pages https://j-chimienti.github.io/lightning-decoder/ 

Website assumes window.location.origin as the homepage which is wrong. It assumes the path is a lightning invoice, which fails to parse and page refresh fails

![Screen Shot 2021-11-19 at 9 08 08 AM](https://user-images.githubusercontent.com/16620120/142635844-6752a4e4-c323-43eb-83c0-374de8b32a81.png)
n`

**Comment by andrerfneves** [comment]
Interesting bug. It seems specific to your deployment scenario which makes the code live under a folder. PRs are always welcome though :)
