### ISSUE TITLE
ln address not resolved

### ISSUE THREAD

**Issue by pseudozach** [andrerfneves/lightning-decoder#75]
trying https://lightningdecoder.com/pseudozach@lntxbot.com I get blank page and below error

![Screen Shot 2022-08-25 at 10 12 47 AM](https://user-images.githubusercontent.com/3731591/186728050-7a60cc7d-4ffb-417d-9c4c-a6d9ea065e00.png)

**Comment by greatzoo** [comment]
Same!

**Comment by snazzybytes** [comment]
Same, not much in the error message itself

**Comment by andrerfneves** [comment]
This has been resolved. It was a bad rendering issue. LNTXBot[dot]com however is no longer.
