### ISSUE TITLE
All LNURL decodes fail due to cors proxy being down

### ISSUE THREAD

**Issue by wbobeirne** [andrerfneves/lightning-decoder#89]
Looks like `https://satcors.fiatjaf.com` is down, which means all lnurl decodes fail right now since they all attempt to use it.

**Comment by SamSamskies** [comment]
+1 bump. @andrerfneves was https://github.com/andrerfneves/lightning-decoder/pull/90 not deployed for some reason?

**Comment by SamSamskies** [comment]
or rather anything holding up https://github.com/andrerfneves/lightning-decoder/pull/87 from being merged?

**Comment by andrerfneves** [comment]
Nothing holding this up apart from finding time. Sorry gents, I just merged it.
